name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal

      - name: Install Trunk
        run: cargo install trunk

      - name: Install jq
        run: sudo apt-get install jq

      - name: Build project
        run: trunk build --release --public-url /

      - name: Generate static pages for routes
        run: |
          cd dist
          while IFS= read -r route; do
            echo "Generating static page for route: $route"
            mkdir -p "$route"
            sed "s|content=\"computools\"|content=\"$route\"|" index.html > "$route/index.html"
          done < <(jq -r '.routes[]' ../routes.json)
          cd ..

      - name: Verify generated pages
        run: |
          cd dist
          echo "Checking generated pages..."
          while IFS= read -r route; do
            if [ -f "$route/index.html" ]; then
              echo "✓ $route/index.html exists"
              if grep -q "content=\"$route\"" "$route/index.html"; then
                echo "✓ $route/index.html has correct meta tag"
              else
                echo "✗ $route/index.html missing correct meta tag"
                exit 1
              fi
            else
              echo "✗ $route/index.html missing"
              exit 1
            fi
          done < <(jq -r '.routes[]' ../routes.json)
          cd ..

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: 'www.compu-tools.com'